== Introduction

Free and open-source software (FOSS) refers to software that is released under a license that grants users the freedom
to run, study, modify, and distribute the software and its source code. Common licenses include GPL,footnote:[https://www.gnu.org/licenses/gpl-3.0.html] MIT,footnote:[https://opensource.org/license/mit] Apache,footnote:[https://www.apache.org/licenses/LICENSE-2.0] BSD,
and many others, a comprehensive list of which is maintained by the Open Source Initiative (OSI).footnote:[https://opensource.org/licenses] Throughout this document, the terms "FOSS" and "open source" are used interchangeably for readability, though they carry distinct philosophical emphases.footnote:[The Free Software Foundation emphasises the ethical dimension of software freedom, while the Open Source Initiative focuses on the practical benefits of open development. In most practical contexts the terms refer to the same body of software and licences.] Such software has become increasingly crucial for WMO and its Members.  No longer a "niche" industry,
FOSS now powers major initiatives and services worldwide, and is backed by industry support.

FOSS solutions play a pivotal role as accelerators for the implementation of Early Warnings for All (EW4All), a key WMO initiative aimed at protecting every person on Earth with life-saving early warning systems by 2027. By providing accessible, customizable, and cost-effective tools, FOSS enables Members to rapidly deploy and adapt early warning systems to their specific needs and contexts. This approach is particularly crucial for least developed countries (LDCs) and small island developing States (SIDS), where resource constraints often hinder the implementation of proprietary solutions. 

Moreover, FOSS initiatives serve as powerful catalysts in supporting Members' efforts towards digital transformation. As National Meteorological and Hydrological Services (NMHSs) worldwide strive to modernize their operations and services, FOSS now offers a flexible and scalable foundation for innovation. They enable Members to leverage cutting-edge technologies, collaborate on development, and share best practices, thus accelerating their digital transformation journeys while optimizing resource utilization.

=== Audience

The document is intended for WMO Members who are involved in software acquisition, implementation and development activities in their respective organizations (developers, managers/decision makers) as well as the WMO Secretariat in the coordination, alignment and support of FOSS within WMO.

=== Scope

This document provides guidance on FOSS for WMO Members and WMO Secretariat, both in terms of using FOSS but also
in the development and contribution to FOSS projects. The guidance is equally applicable to internally developed
software, and to commercially sourced or supported software.

=== Background

FOSS development and use among WMO Members has been a longstanding activity.  Typical FOSS implementations included decoders and encoder libraries of WMO BUFR and GRIB formats (for example, ecCodes, degrib, libecbufr), as well as data dissemination services (such as THREDDS, GDAL, ERDDAP). 

In addition, as part of the global open data/open science movement, numerous government organizations have put forth using FOSS by default; this includes use of existing FOSS tools as well as developing them and working in the open by default.  Free software development platforms and tools (for example, GitHub) have greatly lowered the barrier for sharing software for research, development and operations for all.

As part of the development of the WMO Information System (WIS2), FOSS implementation has been a significant activity, as exemplified by a number of Reference Implementations of WIS2 Standards and Global Services. The development of software in the open during the pre-operational phases of WIS2 proved valuable in testing WIS2 Standards put forth in Technical Regulations while they were still in development. This also promoted the “release early, release often” philosophy of agile and iterative development (see <<_case_study_wis2_foss_and_agile_development>>).
While FOSS is increasingly used across WMO Member organizations, guidance and coordination are vital to support the delivery of services with security, privacy and safety in mind.

==== Culture and process in FOSS projects

Openly developed FOSS projects depend on community contributions and maintainer review and approval of contributions. Whether a large or small community, ongoing maintenance of a project depends on building and maintaining a strong community with a culture of collaboration and contribution. The community aspects of a project can be as important as the technical aspects when considering the maintainability and sustainability of the project.

Communication during the contribution and review process is key. Contributors should consider the effort involved in reviewing contributions and how they can structure their contributions to simplify the process. Contributors should be able to justify all changes they are submitting (whether developed with or without assistance from AI tools).

=== Data policy considerations

While Free and Open Source Software (FOSS) is a key enabler of modern meteorological systems, its full value is realized
only when combined with accessible, well-governed data. Open data and FOSS are mutually reinforcing: open data provides
the raw material for analysis and forecasting, while FOSS provides the tools to discover, process, share, and
operationalize that data. Open data policy has existed for decades at global, regional and national levels (see <<annex-data-policies, Annex B>> for examples).  Together with FOSS they can, for example, support the implementation of the
WMO Unified Data Policyfootnote:[https://wmo.int/wmo-unified-data-policy-resolution-res1] by helping Members expand access to
Earth system data, strengthen international collaboration and contribute to broader open science practices.

==== Open data as a strategic asset

Open data, and especially meteorological, hydrological, atmosphere, and climate data should not be understood solely as
data that is “available”. To be truly useful, data must be governed through clear policy frameworks, standards, and
licensing arrangements that define how it can be accessed, shared, reused, and redistributed. Open access alone does not
guarantee value. Data must also be FAIR:

- *Findable* through clear metadata and catalogues
- *Accessible* through reliable services and standard interfaces
- *Interoperable* across institutions and systems
- *Reusable* under clear legal and technical conditions

These FAIR principles are highly aligned with WMO objectives, provide a practical framework for implementing the Unified
Data Policy, and help ensure that shared data can be effectively used by Members, researchers, and operational
centres, thereby strengthening and supporting also open science and reproducible research.

==== The importance of policy, license and legal clarity

To enable meaningful data exchange, open data should be supported by a clear policy framework. Such policies help
define:

- what data should be shared,
- under what conditions,
- who is responsible for stewardship,
- and how quality, security, and privacy are maintained.

Also, an often overlooked but essential aspect of open data, is licensing. Even where data is technically accessible,
the absence of an explicit open data license can create uncertainty around reuse, redistribution, and related products.
An open data licence helps to provide legal clarity for users and encourages broader adoption. The Open Knowledge
Foundation provides a curated list of open data licences at https://opendefinition.org/licenses/.

==== The enabling role of FOSS

FOSS plays a central role in translating data policy into operational practice.

They can help:

- *Reducing barriers to access*: FOSS tools allow members to access and work with shared datasets without dependence on
costly proprietary software, an aspect especially interesting for members with limited financial or technical resources.

- *Supporting interoperability*: Many FOSS solutions are built around open standards, APIs, and web services, making
data exchange easier (see above).
- *Strengthening transparency*: FOSS workflows allow users to inspect how data are processed, improving trust,
reproducibility, scientific integrity, and metadata management.
- *Enabling innovation*: When open data is combined with open software, organizations can develop locally relevant
applications and services, maybe also supporting start ups and local economies, while contributing improvements back to the wider community.

By relying on open standards and transparent architectures, FOSS helps ensure that data remains interoperable,
portable, and reusable across institutions.

==== The way forward

The benefits of open data policies, such as the WMO Unified Data Policy, depend not only on making data available, but also on
ensuring that data can be effectively discovered, understood, and reused. FOSS provides the technical means to support
this goal, while sound data policies and open licensing provide the governance foundation that ensures sustainable and
trusted data sharing.

Together, open data, FOSS, and open standards can help create a more collaborative, transparent, and resilient global
meteorological data ecosystem.

[[impact-of-ai]]
=== Impact of AI on FOSS Projects

The capabilities of AI/LLM/Agentic tools and workflows are evolving rapidly and increasingly used to contribute to and manage FOSS projects.
FOSS projects can be impacted in a variety of ways including dramatic increases in the number, size, and complexity of contributions.
Many FOSS projects have responded by developing AI Tool Use Policies or Guidelines, often focused on the importance of maintaining a project's community and culture.
(See <<annex-ai-tool-use, Annex C>> for references to AI in FOSS overview articles and example AI use policies.)

The guidelines tend to focus on the need for human communication around contributions, the value of contributions relative to the effort required by maintainers, and transparency with type and amount of AI tool use indicated.
(Contributions of low value-to-effort are sometimes called "extractive contributions".)

The speed and scale at which AI tools can generate possible fixes and enhancements, as well as exploits to security vulnerabilities, necessitates strong culture, process, and communication around human decision making on discussions and issues.
AI has also be used for reputation building through AI-generated discussions and Q&A which, along with requiring maintainer effort, can impact an OSS project's ability to provide support to the user and developer community.
